package models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonDeserialize(builder = models.BookingDates.BookingDatesBuilder.class)
public class BookingDates {
    private String checkin;
    private String checkout;

    @JsonPOJOBuilder(withPrefix = "")
    public static class BookingDatesBuilder {
        // Builder will be generated by Lombok
    }
} 